# Generated by Django 4.2.6 on 2023-11-04 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aluno',
            new_name='Usuario',
        ),
    ]
