# Generated by Django 4.2.6 on 2023-11-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_usuarios_delete_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
